"""Regression tests generated by the durable repair agent."""

import os
from pathlib import Path
import sys
import unittest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import main


class RuntimeRegressionTests(unittest.TestCase):
    def setUp(self):
        self.previous_database_url = main.DATABASE_URL
        self.previous_secret = os.environ.get(main.REQUIRED_ENV_NAME)
        main.DATABASE_URL = "postgresql://ci:ci@unused:5432/ci"
        os.environ[main.REQUIRED_ENV_NAME] = "ci-secret"

    def tearDown(self):
        main.ACTIVE_SCENARIOS.clear()
        main.FEATURE_CHECKOUT_ENABLED = True
        main.DATABASE_URL = self.previous_database_url
        if self.previous_secret is None:
            os.environ.pop(main.REQUIRED_ENV_NAME, None)
        else:
            os.environ[main.REQUIRED_ENV_NAME] = self.previous_secret

    def test_bad_database_url_marks_health_unhealthy(self):
        main.ACTIVE_SCENARIOS.add("bad_database_url")

        body = main.health()

        self.assertEqual(body["status"], "unhealthy")
        self.assertFalse(body["checks"]["database"]["ok"])
        self.assertIn("simulated database connection failure", body["checks"]["database"]["message"])


if __name__ == "__main__":
    unittest.main()
