"""Regression tests generated by the durable repair agent."""

from pathlib import Path
import sys
import unittest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import main


class RuntimeRegressionTests(unittest.TestCase):
    def tearDown(self):
        main.ACTIVE_SCENARIOS.clear()
        main.FEATURE_CHECKOUT_ENABLED = True

    def test_bad_database_url_marks_health_unhealthy(self):
        main.ACTIVE_SCENARIOS.add("bad_database_url")

        body = main.health()

        self.assertEqual(body["status"], "unhealthy")
        self.assertFalse(body["checks"]["database"]["ok"])
        self.assertIn("simulated database connection failure", body["checks"]["database"]["message"])


if __name__ == "__main__":
    unittest.main()
